# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-27 15:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mixed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2016, 9, 27, 15, 57, 8, 977806, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
