# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-28 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixed', '0002_document_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='converter',
            field=models.CharField(blank=True, choices=[('N', 'Normal'), ('M', 'Mark Down'), ('S', 'Server List')], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
